### ISSUE TITLE
Add a process_info built-in measurement

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_poller#28]
Now that we have standardized telemetry events to include multiple measurements, I think it becomes a bit more straight-forward to provide an API that provides general process information. In particular, I would like to include `process_info` (with perhaps `port_info` and `ets_info`) coming in the future. My biggest question is how we are going to expose this to users.

One option is to have a `Telemetry.Poller.Measurements` module and have users do something like this:

    {Telemetry.Poller.Measurements, :process_info, [process_name, [:message_queue_len], [:my_app, :event]]}

I do find this API too verbose though. So my other proposal is something like this:

    {:process_info, name: MyApp.Foo, event: [:my_app, :process_data], measurements: [:message_queue_len, :memory]}

Then I would unify vm_measurements and measurements, into a single key like this:

```elixir
          :memory
          | :total_run_queue_lengths
          | {:process_info, keyword()}
          | {module(), function :: atom(), args :: list()}
```

And we would replace `vm_measurements: :default` by `measurements: :default`.

@arkgil thoughts?

**Comment by arkgil** [comment]
@josevalim I like it! Just to be clear, `:memory` translates to `{Telemetry.Measurements, :memory, []}` and `{:process_info, keyword}` to `{Telemetry.Measurements, :process_info, [keyword]}`?

**Comment by josevalim** [comment]
Yeah, something like that. It should be internal, so it doesn't matter much. :)

**Comment by josevalim** [comment]
Pushed!
