### ISSUE TITLE
[Feature Request] Include process count as built-in and default measurement

### ISSUE THREAD

**Issue by Shayon** [beam-telemetry/telemetry_poller#36]
As Fred Herbert wrote in _Stuff Goes Bad: Erlang In Anger_: "Tracking [process count] over time can be extremely helpful to try and characterize load or detect process leaks..."

Adding an additional measurement to Telemetry.Poller to report the process count at periodic intervals could be very useful.  

If we agree this is useful and someone wants to take this on, I would greatly appreciate it as I am personally not incredibly adept at writing Erlang.  If no one is available to take it on, I'll probably give it a try, but it may take me some time :smile: 

Bonus feature: I'm also thinking it would be very neat to be able to poll for a top-list of processes based on reds or memory, similar to :etop, but I understand if this is more niche and maybe not appropriate as a default for this lib.

**Comment by josevalim** [comment]
Yup, let’s do built in process and atom count. :)

**Comment by pablocostass** [comment]
Hey José, I would like to tackle this issue if that's okay with you.

Would it be as simple as getting both counts from `erlang:system_info/1` (i.e., `erlang:system_info(process_count)` and `erlang:system_info(atom_count)`?

**Comment by josevalim** [comment]
Yup. We should include `port_count` too. Perhaps a built-in `system_limits` measurement.
