### ISSUE TITLE
The sampling name is incorrectly used

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_poller#4]
@fishcakez brought to my attention that the name sampling is confusing, especially in regards [to the OpenCensus nomenclature](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md).

To be more precise, the confusion arises because this library provides a "sampling rate", which is a very specific case of sampling, compared to sampling in general.

One option is to rename this library, but we could not come up with a good name. Maybe `telemetry_timer`. In any case, we thought we could raise the topic for debate.

**Comment by josevalim** [comment]
Meanwhile I have updated the docs in d3b9129  to mention it is a time based sampler, [as found in signal processing](https://en.wikipedia.org/wiki/Sampling_(signal_processing)).

**Comment by arkgil** [comment]
Thanks for raising this. Indeed, even though the name is not completely incorrect, it might be confusing. I kind of like "timer", but it might be confused with something which allows to emit "timing" events (similar to Phoenix instrumenters).

**Comment by josevalim** [comment]
My suggestion for the name: `telemetry_poller`, since that's what we do, we are polling some metrics (which are not published).

@arkgil I see that you also started `telemetry_metrics`. What is the goal of the new project? Let's have a call and discuss it so we make sure we don't get the name wrong this time around. :D

**Comment by arkgil** [comment]
@josevalim Poller sounds good!
