### ISSUE TITLE
atom_count missing on macOS Catalina

### ISSUE THREAD

**Issue by dmorneau** [beam-telemetry/telemetry_poller#42]
When using telemetry_poller on OTP-22 + macOS Catalina, I would expect `atom_count` to be included in the `system_counts` event, but it's missing:

```
[Telemetry.Metrics.ConsoleReporter] Got new event!
Event name: vm.system_counts
All measurements: %{port_count: 18, process_count: 310}
All metadata: %{}
```

I suspect the problem is in `rebar.config`:

```
{erl_opts, [{platform_define, "19", 'OTP19'}, debug_info]}.
```

When the platform happens to contain a 19, for instance `22.0-x86_64-apple-darwin19.3.0`, then this matches because the regex isn't constrained to the start of the line. See: https://github.com/erlang/rebar3/issues/2105#issuecomment-502117026

**Comment by arkgil** [comment]
Thank you for the report 👍
