### ISSUE TITLE
Support for dynamically created processes

### ISSUE THREAD

**Issue by pallix** [beam-telemetry/telemetry_poller#53]
My team is creating long-living dynamically created GenServer instances (created with a DynamicSupervisor) when our assets connect to our servers. Looking at the code, and as far as I understand, it is currently not possible to dynamically use telemetry_poller to measure such processes.

Which approach is the best in this case and would that make sense to extend `telemetry_poller` for this use case? It seems to me that adding an `add_measurement` call in `telemetry_poller.erl` would be enough. 

Edit: probably not enough since `process_info/3` takes a name, so this would not work on unnamed process but you get the idea

**Comment by josevalim** [comment]
The poller is just a convenience for calling telemetry. If you own the process, then it is probably best for you to invoke the telemetry events themselves and bypass the poller altogether. For example, the processes can invoke their handle_info time to time to dispatch them. It is actually preferrable to using the poller in said cases!
