### ISSUE TITLE
Allow telemetry 0.4?

### ISSUE THREAD

**Issue by michallepicki** [beam-telemetry/telemetry_poller#66]
Hi!

Is there a particular reason why telemetry 1.0 is required? AFAIK there were no API changes compared to 0.4.

The reason I'm asking is because we're currently in a weird transition moment, where many packages still depend on telemetry `0.4` without allowing `1.0`, so if some packages (like this one) don't allow 0.4, we're forced to specify `1.0` with an override. In my project this succeeds on `mix deps.get` dependency resolution, but unfortunately, other tasks like `mix test` etc fail to start (I'm not exactly sure why but other people may also be hitting this problem).

I think it could be good to specify `~> 0.4 or ~> 1.0`, at least for some time

**Comment by michallepicki** [comment]
This issue may not make much sense in context of this project. I'm pretty sure most packages still depend on `telemetry_poller` 0.4 or 0.5

**Comment by arkgil** [comment]
@michallepicki just for some context, rebar3 doesn't allow projects to specify dependencies using the `or` syntax, so it wasn't possible to allow both versions. I agree, if folks need to use Telemetry 0.4, they can still use Poller 0.4 or 0.5. Thanks!

**Comment by michallepicki** [comment]
Thanks for clarification!
