### ISSUE TITLE
New metric for scheduler usage

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [beam-telemetry/telemetry_poller#67]
Would it make sense to have something like https://github.com/ferd/recon/blob/master/src/recon.erl#L358 in `telemetry_poller_builtin.erl`?

**Comment by josevalim** [comment]
Last time we discussed this, we agreed to only measure commands that do not require turning on system flags. :)

**Comment by paulo-ferraz-oliveira** [comment]
Got it, makes sense. Thanks, @josevalim.
