### ISSUE TITLE
Include limits

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_poller#8]
For atoms, ets, ports and processes. We need to discuss about alarms though, because the value in itself is not enough.

**Comment by arkgil** [comment]
Yes, it would be nice to have some kind of alarms. A value is useful, but only if the system we export metrics to does support them.

**Comment by josevalim** [comment]
Awesome. Can you please take a look at how prometheus/statsd/others do alarms? Then all we need to do is to standardize on an API for the alarms, although it would most likely be part of `telemetry_metrics` and not here. :)

**Comment by tsloughter** [comment]
Why add alarms? Why is it not up to the external system, like alertmanager with prometheus to handle alarms.

**Comment by josevalim** [comment]
@tsloughter that's exactly why this discussion is about. I think the goal is not for us to emit alarms, but rather to investigate if we can define the alarms here and tell the external system that the alarm exists... but the external system would do the job of actually emitting them.

The only thing that would need to change in this library is to possibly include the limit alongside the measurements.

**Comment by tsloughter** [comment]
@josevalim ah, but I'd say that won't work either, at least not without a lot of external work to create something that gets access to the defined alarms and converts to, for example alertmanager's case, to yaml and writes to its config.

**Comment by josevalim** [comment]
@tsloughter I see.

And do you think that including the limits alongside the measurements could be of any use at all by any system?

**Comment by tsloughter** [comment]
Not sure if some of them might at least have the interface to make it possible (guessing hosted service ones would since they'd have an API to upload alert configuration), but I think it is likely not a good pattern in general. Like a deploy or restart might end up replacing the alerts I modified because there was too much noise.

**Comment by binaryseed** [comment]
From the New Relic perspective, alarms / alerting is fully separate from the point of instrumentation for a number of reasons, including:

1) You don't want to have to re-deploy to change alert configuration
2) Alert policies rarely apply to a single instance, usually an entire application or even multiple (apps tagged `team:MyTeam` for example)
3) Most alert evaluation has significant state (ie: a metric goes above a threshold for 5 minutes)

**Comment by josevalim** [comment]
I  think this settles it  and we can pretty much  close this. WDYT @arkgil ?

**Comment by arkgil** [comment]
@josevalim yeah, agreed. Thanks for your valuable input @tsloughter and @binaryseed! 🙂
